# Generated by Django 4.0.2 on 2022-04-07 20:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('formula', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True)),
                ('CASno', models.CharField(blank=True, max_length=300, null=True)),
                ('molwt', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViscosityofIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('VsTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('VsTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViscosityofIOl', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='VaporViscosityIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('VsTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('VsTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='VaporviscosityIOS', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='VaporThermalofIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('TCTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('TCTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='VaporthermalofIOS', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='Vapor_Pressure_Of_IOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('PTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('PTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vapor_pressure_Of_IOL', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='ThermalConductivityofIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('TCTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('TCTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ThermalconductivityofIOL', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='HeatofVaporizationOIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1x07', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('HvTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('HvTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeatofvaporizationOIOL', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='HeatCapacityOIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqn', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2000, null=True)),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTminE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTmaxE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeatcapacityOIOL', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='HeatCapacityAtConstantPOIOLpolynomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4E05', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5E10', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTminE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTmaxE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeatcapacityAtConstantPOIOLpolynomial', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='HeatCapacityAtConstantPOIOLhyperbolic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3E03', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4E05', models.CharField(blank=True, max_length=2000, null=True)),
                ('C5', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTminE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('CpTmaxE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeatcapacityAtConstantPOIOLhyperbolic', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='EnthalpyandGibbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdealgasEnthalpyE07', models.CharField(blank=True, max_length=2000, null=True)),
                ('IdealgasGibbsE07', models.CharField(blank=True, max_length=2000, null=True)),
                ('IdealgasEntropyE05', models.CharField(blank=True, max_length=2000, null=True)),
                ('StandardnetEnthalpyE09', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enthalpyandgibbs', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='DensityOfIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.CharField(blank=True, max_length=2000, null=True)),
                ('C2', models.CharField(blank=True, max_length=2000, null=True)),
                ('C3', models.CharField(blank=True, max_length=2000, null=True)),
                ('C4', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('DTmin', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('DTmax', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='DensityOfIOl', to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalConstantsAndAFIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tc', models.CharField(blank=True, max_length=2000, null=True)),
                ('Pc', models.CharField(blank=True, max_length=2000, null=True)),
                ('Vc', models.CharField(blank=True, max_length=2000, null=True)),
                ('Zc', models.CharField(blank=True, max_length=2000, null=True)),
                ('AccentricFactor', models.CharField(blank=True, max_length=2000, null=True)),
                ('el', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CriticalconstantsAndAFIOC', to='core.element')),
            ],
        ),
    ]
