# Generated by Django 4.0.2 on 2022-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_element_molwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='densityofiol',
            name='eqn',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2000, null=True),
        ),
    ]
